Move utility methods into a utils module
jaketf/bigquery-utils pull request #1
Opened 2020-12-04 21:12 UTC by RyandenOtter

Change the tests to use new utils module.

2020-12-04 22:03 UTC, jaketf requested changes

2020-12-04 22:03 UTC, jaketf commented on tools/cloud_functions/gcs_event_based_ingest/gcs_ocn_bq_ingest/main.py
> +from .utils import (DEFAULT_JOB_LABELS, SUCCESS_FILENAME, cached_get_bucket,
style: let's just make this
```python3
import .utils as utils
```
and then use the prefix everywhere functions are used 
e.g.
```python3
utils.create_job_id_prefix(...)
```
Reasoning: google style guide for imports https://google.github.io/styleguide/pyguide.html#22-imports

nit: let's make another module for constants and move them all there.
Reasoning: We might add more modules that depend on these constants which are not really utilities.

DEFAULT_JOB_LABELS
SUCCESS_FILENAME
DEFAULT_DESTINATION_REGEX
CLIENT_INFO
JOB_POLL_INTERVAL_SECONDS
BASE_LOAD_JOB_CONFIG 
DEFAULT_MAX_BATCH_BYTES
MAX_SOURCE_URIS_PER_LOAD
SUCCESS_FILENAME
DEFAULT_JOB_PREFIX

2020-12-04 23:53 UTC, RyandenOtter commented on tools/cloud_functions/gcs_event_based_ingest/gcs_ocn_bq_ingest/main.py
> +from .utils import (DEFAULT_JOB_LABELS, SUCCESS_FILENAME, cached_get_bucket,
I made the updates requested

2020-12-05 00:24 UTC, jaketf approved these changes
LGTM

2020-12-05 00:24 UTC, merged